name: Setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
        cache: yarn

    - uses: actions/cache@v3
      id: install-cache
      with:
        path: node_modules/
        key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock', '**/package.json') }}

    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: yarn install --ignore-scripts
      shell: bash

    # --quiet disables all output and makes the program exit with codes similar to diff(1)
    # e.g. exits with 1 if there are differences and 0 if there are no differences
    - run: git diff --quiet -- yarn.lock
      shell: bash
